version: "3.8"

services:
  onlyoffice-oauth-authorization:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${OAUTH_DOCKERFILE}
      args: 
        - MODULE=authorization/authorization-container
    container_name: ${OAUTH_AUTHORIZATION_CONTAINER_NAME}
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_APPLICATION_NAME=ASC.Identity.Authorization
      - SERVER_PORT=8080
      - JDBC_PASSWORD=my-secret-pw
      - JDBC_URL=onlyoffice-mysql-server
      - JDBC_USER_NAME=root
      - JDBC_DATABASE=docspace
      - RABBIT_HOST=onlyoffice-rabbitmq
      - REDIS_HOST=onlyoffice-redis
    depends_on:
      - onlyoffice-oauth-migration

  onlyoffice-oauth-api:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${OAUTH_DOCKERFILE}
      args: 
        - MODULE=registration/registration-container
    container_name: ${OAUTH_API_CONTAINER_NAME}
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_APPLICATION_NAME=ASC.Identity.Registration
      - SERVER_PORT=9090
      - JDBC_PASSWORD=my-secret-pw
      - JDBC_URL=onlyoffice-mysql-server
      - JDBC_USER_NAME=root
      - JDBC_DATABASE=docspace
      - RABBIT_HOST=onlyoffice-rabbitmq
      - REDIS_HOST=onlyoffice-redis
    depends_on:
      - onlyoffice-oauth-migration

  onlyoffice-oauth-migration:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${OAUTH_DOCKERFILE}
      args: 
        - MODULE=infrastructure/infrastructure-migration-runner
    container_name: ${OAUTH_MIGRATION_CONTAINER_NAME} 
    restart: "no"
    ports:
      - 8081:8081
    environment:
      - JDBC_PASSWORD=my-secret-pw
      - JDBC_URL=onlyoffice-mysql-server
      - JDBC_USER_NAME=root
      - JDBC_DATABASE=docspace
      - RABBIT_HOST=onlyoffice-rabbitmq
      - REDIS_HOST=onlyoffice-redis
networks:
  default:
    name: ${NETWORK_NAME}
    external: true
