version: "3.8"

services:
  onlyoffice-oauth-authorization:
    build:
      context: ../../../server/common/ASC.OAuth
      dockerfile: ${OAUTH_AUTHORIZATION_DOCKERFILE}
    container_name: ${OAUTH_AUTHORIZATION_CONTAINER_NAME}
    restart: always
    ports:
      - 8080:8080
    environment:
      PROFILE: ${PROFILE}
      JDBC_URL: ${MYSQL_CONTAINER_NAME}
      JDBC_DATABASE: ${MYSQL_DATABASE}
      JDBC_USER_NAME: ${JDBC_USER_NAME}
      JDBC_PASSWORD: ${JDBC_PASSWORD}
      RABBIT_HOST: ${RABBIT_CONTAINER_NAME}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER_NAME: ${RABBIT_USER_NAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
  onlyoffice-oauth-api:
    build:
      context: ../../../server/common/ASC.OAuth
      dockerfile: ${OAUTH_API_DOCKERFILE}
    container_name: ${OAUTH_API_CONTAINER_NAME}
    ports:
      - 9090:9090
      - 8585:8585
    environment:
      PROFILE: ${PROFILE}
      JDBC_URL: ${MYSQL_CONTAINER_NAME}
      JDBC_DATABASE: ${MYSQL_DATABASE}
      JDBC_USER_NAME: ${JDBC_USER_NAME}
      JDBC_PASSWORD: ${JDBC_PASSWORD}
      RABBIT_HOST: ${RABBIT_CONTAINER_NAME}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER_NAME: ${RABBIT_USER_NAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
networks:
  default:
    name: ${NETWORK_NAME}
    external: true
