name: 4testing multiarch-build

on:
  push:
    branches: ["release/v1.0.0"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build 4testing
        run: |
          export BUILD_NUMBER="$(date "+%Y%m%d%H")"
          cd ./build/install/docker
          REPO="onlyoffice" \
          DOCKER_IMAGE_PREFIX="4testing-docspace" \
          DOCKER_TAG=v1.0.0 \
          DOCKERFILE="Dockerfile.app" \
          docker buildx bake -f build.yml \
          --set *.args.GIT_BRANCH=$GITHUB_REF_NAME \
          --set *.platform=linux/amd64 \
          --push
          REPO="onlyoffice" \
          DOCKER_IMAGE_PREFIX="4testing-docspace" \
          DOCKER_TAG=v1.0.0-$BUILD_NUMBER \
          DOCKERFILE="Dockerfile.app" \
          docker buildx bake -f build.yml \
          --set *.args.GIT_BRANCH=$GITHUB_REF_NAME \
          --push
        shell: bash
