name: 4testing multiarch-build

on:
  push:
    branches: 
      - 'hotfix/v**'
      - 'release/v**'
      - 'feature/*-build-action'
env:
    DOCKER_PATH: "/build/install/docker"
    REPO: "onlyoffice"
    DOCKER_IMAGE_PREFIX: "4testing-docspace"
    DOCKERFILE: "Dockerfile.app"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build 4testing
        run: |
          cd .${DOCKER_PATH}
          DOCKER_TAG=$(echo "${GITHUB_REF_NAME}" | sed '/^release\b\|^hotfix\b/s/release.*\/\|hotfix.*\///; s/-build-action$//').${{github.run_number}}
          if [[ $GITHUB_REF_NAME =~ feature/(.*)-build-action ]]; then
            DOCKER_TAG=$(echo "${GITHUB_REF_NAME}" | sed -E "s|feature/(.*)-build-action|\1-action|")
          fi
          export DOCKER_TAG       

          docker buildx bake -f build.yml \
          --set *.args.GIT_BRANCH=$GITHUB_REF_NAME \
          --set *.platform=linux/amd64 \
          --push
        shell: bash
